### ISSUE TITLE
Thread deadlock with Bigwarp or edit last registration

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/abba_python#33]
The manual lock is never acquired... And it doesn't seem to be a problem in pure Java in the IDE.

I tried to force abba python to use org.scijava:scijava-ui-swing:jar:1.0.1:compile

But it doesn't work:

```
[ERROR] Malfunctioning plugin: org.scijava.ui.swing.widget.SwingObjectWidget
java.lang.NullPointerException
	at org.scijava.widget.WidgetModel.getChoices(WidgetModel.java:140)
	at org.scijava.ui.swing.widget.SwingObjectWidget.supports(SwingObjectWidget.java:101)
	at org.scijava.ui.swing.widget.SwingObjectWidget.supports(SwingObjectWidget.java:54)
	at org.scijava.plugin.TypedService.find(TypedService.java:70)
	at org.scijava.plugin.WrapperService.create(WrapperService.java:64)
	at org.scijava.widget.AbstractInputHarvester.addInput(AbstractInputHarvester.java:110)
	at org.scijava.widget.AbstractInputHarvester.buildPanel(AbstractInputHarvester.java:84)
	at org.scijava.widget.InputHarvester.harvest(InputHarvester.java:67)
	at org.scijava.ui.AbstractInputHarvesterPlugin.process(AbstractInputHarvesterPlugin.java:74)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:103)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:154)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Edit last registration command called.
Edit registration:Edition will begin when the manual lock is acquire
```

**Comment by NicoKiaru** [comment]
Wrong diagnosis - the problem was the lack of n5 dependencies, which has been fixed in a later commit
