### ISSUE TITLE
Export to Qupath does not work in headless mode from a script

### ISSUE THREAD

**Issue by GuillaumeLeGoc** [BIOP/abba_python#9]
* ABBA Python version: 0.3.0
* Python version: 3.7.16
* Operating System: Windows 10

### Description

I want to export registration to the Qupath project programmatically from python.
To do this, I launch an ABBA instance in headless mode, I load a state file and run the export registration command :
```
aligner = abba.Abba('Adult Mouse Brain - Allen Brain Atlas V3p1', headless=True)
aligner.state_load(os.path.join(inputdir, inputfile))
aligner.select_all_slices()
aligner.export_registration_to_qupath(erase_previous_file=True)
```
The following line is printed : 
`Exporting slice img_001.ome.tiff registration to QuPath`
But there is nothing written in the Qupath project.

There is an error raised during the loading of the state file (see below), but this error did not prevent me from doing things with abba_python previously (eg. converting coordinates).

Doing the same thing not in headless mode (eg. `aligner = abba.Abba('Adult Mouse Brain - Allen Brain Atlas V3p1')`), the output is more talkative, those lines are also printed :
```
Multipositioner : Save slice ROI to quPath project path\to\qproj\data\1\ABBA-RoiSet-Adult Mouse Brain - Allen Brain Atlas V3p1.zip
Multipositioner : Save transformation to quPath project path\to\qproj\data\1\ABBA-Transform-Adult Mouse Brain - Allen Brain Atlas V3p1.json
```

And the files are indeed exported.

So it seems the multipositionner does not really exist in headless mode and Qupath export relies on it (but converting coordinates does not so that is why the latter works) ?

### Output
```
[java.lang.Enum.toString] [ERROR] Multipositioner : null
[ERROR] Command errored: ABBA - Load State
java.awt.HeadlessException
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at ch.epfl.biop.atlas.aligner.MultiSlicePositioner.lambda$new$2(MultiSlicePositioner.java:134)
        at ch.epfl.biop.atlas.aligner.MultiSlicePositioner.lambda$new$4(MultiSlicePositioner.java:144)
        at ch.epfl.biop.atlas.aligner.MultiSlicePositioner.loadState(MultiSlicePositioner.java:1181)
        at ch.epfl.biop.atlas.aligner.command.ABBAStateLoadCommand.run(ABBAStateLoadCommand.java:27)
        at org.scijava.command.CommandModule.run(CommandModule.java:196)
        at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
        at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[java.lang.Enum.toString] [ERROR] Command errored: ABBA - Load State
java.awt.HeadlessException
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:189)
        at ch.epfl.biop.atlas.aligner.MultiSlicePositioner.lambda$new$2(MultiSlicePositioner.java:134)
        at ch.epfl.biop.atlas.aligner.MultiSlicePositioner.lambda$new$4(MultiSlicePositioner.java:144)
        at ch.epfl.biop.atlas.aligner.MultiSlicePositioner.loadState(MultiSlicePositioner.java:1181)
        at ch.epfl.biop.atlas.aligner.command.ABBAStateLoadCommand.run(ABBAStateLoadCommand.java:27)
        at org.scijava.command.CommandModule.run(CommandModule.java:196)
        at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
        at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by NicoKiaru** [comment]
> But there is nothing written in the Qupath project.

Just to be sure: you do not see any file in the project entry ?

**Comment by NicoKiaru** [comment]
Yeah, I read more carefully your message and got it, that's why I deleted my message sorry !

I'll need a bit of time, debugging in python is not sure super straightforward

**Comment by NicoKiaru** [comment]
I've looked quickly and there's no clear dependency on the user interface.
I'll have to dig more carefully

**Comment by NicoKiaru** [comment]
First (the not important one: I had a bunch of graphical classes for logging even in the one that's suppose to work headless). So I'll remove them.

**Comment by NicoKiaru** [comment]
Ah! Then I think the issue comes from the asynchronous nature of the method.

Please try to add at the end of your script:

```
# all tasks/registrations/exports are enqueued and executed asynchronously
# if you want to wait that all tasks are finished, then add:
aligner.wait_for_end_of_tasks()
```

If that's the issue, then I need to change the method or improve the documentation. Probably I'll add an extra parameter `async` that would be false by default.

**Comment by NicoKiaru** [comment]
Reopening the issue to keep track of the documentation modification

**Comment by NicoKiaru** [comment]
Hi @GuillaumeLeGoc  and thanks for the report!

> It feels like I'm either the only one to use it, the only one to complain or the only for who it does not work as expected :'(

:-) Yes, there's much less users in python than within the regular Fiji. You may be the only one or not far from it.

I'm not sure about this new issue. I'll try to contact you by email

**Comment by greenpolo** [comment]
test
